packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  "@types/node": ^20.14.15
  "@tailwindcss/typography": "^0.5.15"
  "@next/eslint-plugin-next": ^14.2.5
  "@heroicons/react": ^2.1.5
  "@t3-oss/env-nextjs": ^0.10.1
  "dotenv-cli": ^7.4.2
  "@polkadot/api": ^13.0.1
  "@polkadot/util": ^13.0.2
  "@polkadot/util-crypto": ^13.0.2
  "@polkadot/types": ^13.0.1
  "@polkadot/api-augment": ^13.0.1
  "@polkadot/extension-dapp": ^0.52.3
  "@polkadot/extension-inject": ^0.52.3
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  postcss: ^8.4.41
  typescript: ^5.5.4
  zod: ^3.23.8
  jiti: ^1.21.6
  next: ^14.2.13
  rustie: ^0.2.0
  tsafe: ^1.6.6
  multiformats: ^13.2.3
  tsx: ^4.19.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
