packages:
  - apps/*
  - services/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.5.0
  "@trpc/react-query": ^11.5.0
  "@trpc/server": ^11.5.0
  "@types/node": ^20.14.15
  "@tailwindcss/typography": "^0.5.15"
  "@next/eslint-plugin-next": ^16.0.0
  "@t3-oss/env-nextjs": ^0.10.1
  "dotenv-cli": ^7.4.2
  "react-hook-form": ^7.53.2
  "@hookform/resolvers": ^3.9.1
  "motion": ^12.23.19
  "recharts": ^2.15.4
  "@polkadot/api": ^14.2.3
  "@polkadot/keyring": ^13.4.3
  "@polkadot/util": ^13.2.1
  "@polkadot/util-crypto": ^13.2.1
  "@polkadot/typegen": ^14.2.3
  "@polkadot/types": ^14.2.3
  "@polkadot/api-augment": ^14.2.3
  "@polkadot/extension-dapp": ^0.52.3
  "@polkadot/extension-inject": ^0.52.3
  "@next/third-parties": ^15.2.3
  "eslint": ^9.9.0
  "prettier": ^3.3.3
  "tailwindcss": ^3.4.10
  "postcss": ^8.4.41
  "typescript": ^5.5.4
  "zod": ^3.25.0
  "zustand": ^5.0.6
  "jiti": ^1.21.6
  "ky": ^1.10.0
  "next": ^16.0.7
  "rustie": ^0.4.0
  "tsafe": ^1.6.6
  "multiformats": ^13.2.3
  "tsx": ^4.19.1
  "luxon": ^3.5.0
  "lucide-react": ^0.475.0
  "vitest": ^3.2.4
  "emittery": ^1.2.0
  "@uidotdev/usehooks": ^2.4.1
  "superjson": ^2.2.1
  # Hyperlane
  "viem": ^2.22.1
  "next-plausible": ^3.12.4
  # 3D
  "@react-three/fiber": ^9.4.0
  "@react-three/drei": ^10.7.6
  "@react-three/postprocessing": ^3.0.4
  "three": ^0.180.0
  "@types/three": ^0.180.0
  "postprocessing": ^6.37.8

catalogs:
  react18:
    "react": "~18.2.0"
    "react-dom": "~18.2.0"
    "@types/react": "~18.2.0"
    "@types/react-dom": "~18.2.0"
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "~19.0.12"
    "@types/react-dom": "~19.0.4"
