-- Create enum type "distribution_type"
CREATE TYPE "public"."distribution_type" AS ENUM ('MANUAL', 'AUTOMATIC', 'AT_BLOCK', 'INTERVAL');
-- Create enum type "permission_scope_type"
CREATE TYPE "public"."permission_scope_type" AS ENUM ('EMISSION');
-- Create "emission_streams" table
CREATE TABLE "public"."emission_streams" ("id" serial NOT NULL, "streams_uuid" uuid NOT NULL DEFAULT gen_random_uuid(), "permission_id" character varying(66) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "emission_streams_permission_id_unique" UNIQUE ("permission_id"), CONSTRAINT "emission_streams_streams_uuid_unique" UNIQUE ("streams_uuid"));
-- Create "emission_streams_details" table
CREATE TABLE "public"."emission_streams_details" ("id" serial NOT NULL, "streams_uuid" uuid NOT NULL, "permission_id" character varying(66) NOT NULL, "stream_id" character varying(66) NOT NULL, "percentage" integer NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "emission_streams_details_permission_id_emission_streams_permiss" FOREIGN KEY ("permission_id") REFERENCES "public"."emission_streams" ("permission_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "emission_streams_details_streams_uuid_emission_streams_streams_" FOREIGN KEY ("streams_uuid") REFERENCES "public"."emission_streams" ("streams_uuid") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "permission_emission_scope" table
CREATE TABLE "public"."permission_emission_scope" ("id" serial NOT NULL, "permission_id" character varying(66) NOT NULL, "streams_uuid" uuid NOT NULL, "distribution_type" "public"."distribution_type" NOT NULL, "distribution_info" numeric NULL, "accumulating" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "permission_emission_scope_permission_id_unique" UNIQUE ("permission_id"), CONSTRAINT "permission_emission_scope_streams_uuid_unique" UNIQUE ("streams_uuid"), CONSTRAINT "permission_emission_scope_permission_id_emission_streams_permis" FOREIGN KEY ("permission_id") REFERENCES "public"."emission_streams" ("permission_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "permission_emission_scope_streams_uuid_emission_streams_streams" FOREIGN KEY ("streams_uuid") REFERENCES "public"."emission_streams" ("streams_uuid") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "permission" table
CREATE TABLE "public"."permission" ("id" serial NOT NULL, "permission_id" character varying(66) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "permission_permission_id_unique" UNIQUE ("permission_id"), CONSTRAINT "permission_permission_id_permission_emission_scope_permission_i" FOREIGN KEY ("permission_id") REFERENCES "public"."permission_emission_scope" ("permission_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "enforcement_authority" table
CREATE TABLE "public"."enforcement_authority" ("id" serial NOT NULL, "permission_id" character varying(66) NOT NULL, "ss58_address" character varying(256) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "enforcement_authority_permission_id_permission_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "public"."permission" ("permission_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "constraint" table
CREATE TABLE "public"."constraint" ("id" serial NOT NULL, "body" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create "permission_details" table
CREATE TABLE "public"."permission_details" ("id" serial NOT NULL, "permission_id" character varying(66) NOT NULL, "grantor_key" character varying(256) NOT NULL, "grantee_key" character varying(256) NOT NULL, "scope" "public"."permission_scope_type" NOT NULL, "duration" numeric NOT NULL, "revocation" integer NOT NULL, "last_execution" timestamptz NULL DEFAULT now(), "execution_count" numeric NOT NULL, "parent_id" character varying(66) NULL, "constraint_id" integer NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "permission_details_permission_id_unique" UNIQUE ("permission_id"), CONSTRAINT "permission_details_constraint_id_constraint_id_fk" FOREIGN KEY ("constraint_id") REFERENCES "public"."constraint" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "permission_details_permission_id_permission_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "public"."permission" ("permission_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
