environments:
  dev:
    values:
      - ../../helm/values.yaml
      - values.yaml
      - namespace: torus-dev-web-apps
      - environmentName: dev
      - wssApiEndpoint: wss://testnet.api.communeai.net # TODO: change this to the Torus API when launched
      - cacheUrl: https://dev.cache.torus.network
      - releaseName: dev-torus-page
      - ingressHost: dev.torus.network
  prod:
    values:
      - ../../helm/values.yaml
      - values.yaml
      - namespace: torus-prod-web-apps
      - environmentName: prod
      - wssApiEndpoint: wss://api.communeai.net # TODO: change this to the Torus API when launched
      - cacheUrl: https://cache.torus.network
      - releaseName: torus-page
      - ingressHost: torus.network
---
helmDefaults:
  wait: true
  createNamespace: false

repositories:
  - name: renlabs
    url: https://charts.renlabs.dev/

releases:
  - name: "{{ .Values.releaseName }}"
    namespace: "{{ .Values.namespace }}"
    chart: renlabs/application
    values:
      - ../../helm/values.yaml.gotmpl
      - ingress:
          hosts:
            - host: "{{ .Values.ingressHost }}"
              paths:
                - path: /
                  pathType: Prefix
