deployment:
  image:
    repository: ghcr.io/renlabs-dev/torus-page

  podLabels:
    app: torus-page

    NEXT_PUBLIC_TORUS_CHAIN_ENV:
      valueFrom:
        configMapKeyRef:
          name: '{{ template "application.name" . }}-config'
          key: torus_chain_env
