deployment:
  image:
    repository: ghcr.io/renlabs-dev/torus-page

  additionalLabels:
    app: torus-page

  podLabels:
    app: torus-page

  env:
    NEXT_PUBLIC_TORUS_ALLOCATOR_ADDRESS:
      valueFrom:
        configMapKeyRef:
          name: '{{ template "application.name" . }}-config'
          key: torus_allocator_address
