name: "Turbo Setup (no deps install)"
description: "Minimal setup for Turbo change detection - no dependency installation"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Turbo globally
      shell: bash
      run: |
        # Install turbo globally to avoid pnpm dependency installation
        npm install -g turbo@^2.3.3
        echo "Turbo version: $(turbo --version)"
