environments:
  dev:
    values:
      - ../../helm/values.yaml
      - values.yaml
      - namespace: torus-dev-web-apps
      - environmentName: dev
      - wssApiEndpoint: wss://api.testnet.torus.network
      - cacheUrl: https://cache.testnet.torus.network
      - apiBaseUrl: https://memory.sension.torus.directory/api/
      - releaseName: dev-torus-prediction-swarm-dashboard
      - ingressHost: dev.sension.torus.directory
      - chainEnv: testnet
  prod:
    values:
      - ../../helm/values.yaml
      - values.yaml
      - namespace: torus-prod-web-apps
      - environmentName: prod
      - wssApiEndpoint: wss://api.torus.network
      - cacheUrl: https://cache.torus.network
      - apiBaseUrl: https://memory.sension.torus.directory/api/
      - releaseName: torus-prediction-swarm-dashboard
      - ingressHost: sension.torus.directory
      - chainEnv: mainnet
---
helmDefaults:
  wait: true
  createNamespace: false

repositories:
  - name: renlabs
    url: https://charts.renlabs.dev/

releases:
  - name: "{{ .Values.releaseName }}"
    namespace: "{{ .Values.namespace }}"
    chart: renlabs/application
    values:
      - ../../helm/values.yaml.gotmpl
      - ingress:
          hosts:
            - host: "{{ .Values.ingressHost }}"
              paths:
                - path: /
                  pathType: Prefix
