# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0x1c87f74D6E39F567cB1aac0e091Dc433a702ABd7"
    chainName: basesepolia
    connections:
      - token: ethereum|torustestnet|0x677723050085BFE889726B58a14418a92cBF7f36
    decimals: 18
    name: torustestnet
    standard: EvmHypSynthetic
    symbol: TORUS
  - addressOrDenom: "0x677723050085BFE889726B58a14418a92cBF7f36"
    chainName: torustestnet
    connections:
      - token: ethereum|basesepolia|0x1c87f74D6E39F567cB1aac0e091Dc433a702ABd7
    decimals: 18
    name: torustestnet
    standard: EvmHypNative
    symbol: TORUS
