# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0x78EC15C5FD8EfC5e924e9EEBb9e549e29C785867"
    chainName: base
    connections:
      - token: ethereum|torus|0x9925CdbeA5B91542bbA6e1fc967465b1C1ED7156
    decimals: 18
    name: Torus
    standard: EvmHypSynthetic
    symbol: TORUS
  - addressOrDenom: "0x9925CdbeA5B91542bbA6e1fc967465b1C1ED7156"
    chainName: torus
    connections:
      - token: ethereum|base|0x78EC15C5FD8EfC5e924e9EEBb9e549e29C785867
    decimals: 18
    name: Torus
    standard: EvmHypNative
    symbol: TORUS
