name: "Import DB Secrets"
description: "Import database secrets from Vault based on environment"

inputs:
  vault_addr:
    description: "Vault address"
    required: true
  vault_role_id:
    description: "Vault role ID"
    required: true
  vault_secret_id:
    description: "Vault secret ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set environment
      id: set-env
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          ENV_NAME=${{ github.event.pull_request.base.ref == 'main' && 'prod' || 'dev' }}
        else
          ENV_NAME=${{ github.ref_name == 'main' && 'prod' || 'dev' }}
        fi
        echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT

    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        method: approle
        url: ${{ inputs.vault_addr }}
        roleId: ${{ inputs.vault_role_id }}
        secretId: ${{ inputs.vault_secret_id }}
        secrets: |
          torus_infra/data/${{ steps.set-env.outputs.env_name }}_web_apps torus_webapps_db_direct_url | POSTGRES_URL
