cacheUrl: ""

ingress:
  enabled: false

service:
  enabled: false

deployment:
  image:
    repository: ghcr.io/renlabs-dev/torus-worker

  podLabels:
    app: torus-worker

  command: ["pnpm", "tsx", "./src/index.ts"]

  startupProbe:
    httpGet:
      path: /api/health

  readinessProbe:
    enabled: false

  livenessProbe:
    enabled: false

  env:
    TORUS_ALLOCATOR_MNEMONIC:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: torus_allocator_mnemonic
    POSTGRES_URL:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: torus_webapps_db_url
    CURATOR_DISCORD_WEBHOOK_URL:
      valueFrom:
        secretKeyRef:
          name: "torus-{{ .Values.environmentName }}-web-apps-secret"
          key: curator_discord_webhook_url
