# .github/workflows/debug.yml
name: Check Changes

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/check-turbo-changes
        id: changes

      # Simple conditional steps
      - name: Build torus-wallet
        if: steps.changes.outputs.torus-wallet == 'true'
        run: echo "Building torus-wallet..."

      - name: Build torus-page
        if: steps.changes.outputs.torus-page == 'true'
        run: echo "Building torus-page... "

      # Debug output
      - name: Show changes
        run: |
          # Print all outputs
          echo "All changes:"
          echo '${{ toJSON(steps.changes.outputs) }}' | jq '.'
