name: Dump GH events and payloads

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

jobs:
  check-pr:
    name: Check for existing PR
    runs-on: ubuntu-latest
    outputs:
      pr_exists: ${{ steps.findPr.outputs.number != '' }}
      pr_number: ${{ steps.findPr.outputs.number }}

    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: findPr

      - name: Debug PR info
        run: |
          echo "PR exists: ${{ steps.findPr.outputs.number != '' }}"
          echo "PR number: ${{ steps.findPr.outputs.number }}"

  test:
    name: debug
    needs: check-pr
    runs-on: ubuntu-latest
    if: needs.check-pr.outputs.pr_exists == 'false'

    steps:
      - name: Debug PR status
        run: |
          echo "Running because no PR exists"

      - name: print whole context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
