# .github/workflows/torus-wallet.yml
name: torus-wallet

on:
  pull_request:
    branches-ignore:
      - main
      - dev
    types:
      - opened
      - reopened
      - closed
      - synchronize
    paths-ignore:
      - "apps/torus-page/**"
      - "apps/torus-allocator/**"
      - "apps/torus-bridge/**"
      - "apps/torus-worker/**"
      - "apps/torus-governance/**"

jobs:
  pr-preview-activate:
    if: github.event.pull_request.state == 'open' && !github.event.repository.fork
    uses: ./.github/workflows/pr-preview-template.yml
    secrets: inherit
    with:
      app_name: torus-wallet

  pr-preview-delete:
    if: github.event.pull_request.state == 'closed'
    uses: ./.github/workflows/pr-preview-template.yml
    secrets: inherit
    with:
      app_name: torus-wallet
      delete: true
