# .github/workflows/torus-allocator.yml
name: torus-allocator

on:
  workflow_dispatch:
    inputs:
      skip_build:
        required: false
        description: "Skip Docker Build"
        type: boolean
        default: false
  push:
    paths-ignore:
      - "apps/torus-governance/**"
      - "apps/torus-page/**"
      - "apps/torus-bridge/**"
      - "apps/torus-wallet/**"
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize
    paths-ignore:
      - "apps/torus-governance/**"
      - "apps/torus-page/**"
      - "apps/torus-bridge/**"
      - "apps/torus-wallet/**"

jobs:
  kubernetes:
    if: github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'cicd'
    uses: ./.github/workflows/app-deployment-template.yml
    secrets: inherit
    with:
      app_name: torus-allocator
      skip_build: ${{ inputs.skip_build || false }}

  dry-run-build:
    if: github.ref_name != 'main' && github.ref_name != 'dev' && github.ref_name != 'cicd'
    uses: ./.github/workflows/dry-run-build-template.yml
    with:
      app_name: torus-allocator

  pr-preview-activate:
    if: github.event.pull_request.state == 'open' && !github.event.repository.fork
    uses: ./.github/workflows/pr-preview-template.yml
    secrets: inherit
    with:
      app_name: torus-allocator

  pr-preview-delete:
    if: github.event.pull_request.state == 'closed'
    uses: ./.github/workflows/pr-preview-template.yml
    secrets: inherit
    with:
      app_name: torus-allocator
      delete: true
