# .github/workflows/torus-worker.yml
name: torus-worker

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "apps/torus-allocator/**"
      - "apps/torus-governance/**"
      - "apps/torus-page/**"
      - "apps/torus-bridge/**"
      - "apps/torus-wallet/**"
      - "apps/torus-cache/**"

jobs:
  kubernetes:
    if: github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'cicd'
    uses: ./.github/workflows/app-deployment-template.yml
    secrets: inherit
    with:
      app_name: torus-worker

  dry-run-build:
    if: github.ref_name != 'main' && github.ref_name != 'dev' && github.ref_name != 'cicd'
    uses: ./.github/workflows/dry-run-build-template.yml
    with:
      app_name: torus-worker
